[package]
name = "vrp-pragmatic"
version = "1.16.0"
authors = ["Ilya Builuk <ilya.builuk@gmail.com>"]
license = "Apache-2.0"
keywords = ["vrp", "optimization"]
categories = ["algorithms", "science"]
readme = "README.md"
homepage = "https://github.com/reinterpretcat/vrp"
repository = "https://github.com/reinterpretcat/vrp"
edition = "2021"
description = "An extension logic for solving rich VRP"

[dependencies]
vrp-core = { path = "../vrp-core", version = "1.16.0" }

serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"

time = { version = "0.3.7", features = ["parsing", "formatting"] }
rand = "0.8.5"
hashbrown = "0.12.0"

[dev-dependencies]
proptest = "1.0.0"
uuid = { version = "0.8.2", features = ["v4"] }
